### PR TITLE
JENKINS-47919 - fix of 404 and get of build number

### PR DESCRIPTION
**Pull request by jiri-meluzin**
There are two issues with this plugin:
1) it does not properly handle HTTP 404 when reading inputStream and errorStream from URLConnection.
2) it does not recognize build number of the created remote job, it tried to get build number from the list of last jobs, but it does not work very well, usually selects prior job.

### CODE REVIEW

**Comment by cashlalala** [comment]
I think these issues have been fixed now, and I'll close this PR. thx

**Comment by PavanTatikonda** [comment]
@cashlalala do you know the exact version of Jenkins where these issues are fixed ?

**Comment by kutzi** [comment]
I doubt that this is fixed as it's still happening for us:
local Jenkins ver. 2.121.1, remote: Jenkins ver. 2.126

Please reconsider! This bug is making this plugin unusable for us!

**Comment by rpionke** [comment]
@kutzi we are using local Jenkins ver. 2.121.1 and remote Jenkins ver. 2.130 without any problems. Can you please provide the configuration (without internals) for better debugging?

**Comment by kutzi** [comment]
Which configuration do you need? The Job config or the Jenkins config of the remote one?

**Comment by cashlalala** [comment]
It's a bug resulted from the old build number checking who checked the "lastBuild" even if it didn't exist, and it resulted in 404 with incomplete error handling you've seen.  
I just fixed it and will release it sometime.  

BTW, I once thought this issue was fixed by #32  which was run by a company for long time.
I tested it without creating a new job and got no error, so I closed it. My apologies. 
Although it's really easy to workaround, just successfully run you remote jobs in manual at least one time.

**Comment by kutzi** [comment]
In my case the remote job did already run several times, so it's probably not that issue.

Could it be that wrong job names and/or wrong credentials could trigger the NPE as well?

**Comment by cashlalala** [comment]
Would you mind to turn on the debug mode, set up a break point at liine
1103 on commit 11f24e0b807680a6b8e3e5b3db138d401850261c, and check the url
value?
Because I could only consistently reproduce the case I mentioned and fixed
it.
Or you can just add logger for the url to check . ( it would last massive
logs if you have many jobs to run)

**Comment by kutzi** [comment]
Sorry, I've now verified that it were a completey wrong job name in my case.
Would still be good if that could fail with a better error message instead of throwing a NPE

**Comment by cashlalala** [comment]
I've already treated the 404 case with a specific error handling.
You can try the master head version.
If nothing wrong, please tell me and I'm going to release it.

**Comment by cashlalala** [comment]
Thx! gonna release it these two days  & close the Jira ticket.

**Pull request closed without merging**
