### PR TITLE
Allow use `triggerRemoteJob` step with `agent none`

### PR DESCRIPTION
**Pull request by bozaro**
Looks like agent used only if `loadParamsFromFile` attribute defined, but now we always need hold agent for remote job.

### CODE REVIEW

**Comment by cashlalala** [comment]
@bozaro , Would you like to tell me more about the use case? It works for me in this case
image

**Comment by bozaro** [comment]
Example of out usecase.
We have two Jenkins cluster:
 - build jenkins (managed by developers);
 - deploy jenkins (managed by devops).

So, in build jenkins we have job like:
```
pipeline {
    agent none

    stages {
        stage("Build") {
            agent {
                ...
            }
            stages {
                ...
            }
        }
        stage("Deploy") {
            steps {
              triggerRemoteJob job: "deploy", remoteJenkinsName: "deploy_jenkins", maxConn: 5, enhancedLogging: true
            }
        }
    }
}
```

Currently we need to allocate agent for `Deploy` stage. So on `Deploy` we use two executors:
 - first one actually deploy;
 - second one simply wait deploy compeletion.

This patch allow hold only agent with actual work.

**Comment by bozaro** [comment]
Without this patch we have workaround: make some cheap agents with big executors count and specific labels for waiting `triggerRemoteJob`.
But without agent allocation it's little better.

**Comment by LorisFriedel** [comment]
I'm also interested in this improvement, I have the exact same use-case!

**Comment by haoliangyu** [comment]
This is a nice improvement to have. We have the same use case as well.

**Pull request merged**
