### PR TITLE
Fix migration to parameters2

### PR DESCRIPTION
**Pull request by quilicicf**
## What does this PR do?

The [previous PR](https://github.com/jenkinsci/parameterized-remote-trigger-plugin/pull/79) I did was incomplete, this PR gives it the final touches.

The changes are:

* fix the migration from parameters to parameters2 via the UI
* fix pipeline step
* re-order the parameter types to appear in the correct order in the UI
* add documentation

### Migration from parameters to parameters2

The issue was that in `migrateOldParameters`, it was assumed unset parameters were `null` where they are in fact empty.

This means that since the file parameters case was checked first, it was always assumed to be set and the string parameters could never be migrated.

The checks have been updated to make sure empty values are ignored too.

### Pipeline step fix

The pipeline step setters `setParameters` & `setParameterFile` were removed and replaced with `setParameters2(JobParameter)`. 

This was pretty bad for two reasons:

* it broke old job steps using `parameters` or `parameterFile`
* it required good knowledge of the plugin's innards to work as people were expected to know to use configurations like this:
    ```java
    triggerRemoteJob(
      parameters2: [
        $class: 'org.jenkinsci.plugins.ParameterizedRemoteTrigger.parameters2.StringParameters',
        parameters: 'PARAM=value'
      ])
    ```
    Where the `$class` links to the concrete type's fully qualified name and `parameters` is the inner field. Each `JobParameters` implementation having a different name for the inner field that was a pretty terrible API.

I updated the `RemoteBuildPipelineStep` class to use `setParameters` for all type of parameters and instantiate the `JobParameters` from `String` or `Map` instead. This means a single setter can be used without knowing how the plugin is implemented.

The setter `setParameterFile` will be re-added and deprecated to make sure old configurations that used it still work.

The doc will be updated to reflect this.

### Re-order parameter types

I changed the ordinals in JobParameters instances (`@Extension` annotation) to make sure they appear in the correct order in the UI: 

1. `MapParameters`
2. `StringParameters`
3. `FileParameters`

### Documentation

I added/updated HTML documentation for the new parameters.

### CODE REVIEW

**Comment by cashlalala** [comment]
Verified, looks awesome to me especially in new UI in latest jenkins master. lol.

**Comment by quilicicf** [comment]
Cool :) 
The UI has indeed changed a lot. 
Took a trip down memory lane working with Jenkins `1.642.3` :rofl:

**Comment by priyanka-kaur** [comment]
Hey, can you provide an example to pass a multiline string using Map parameter to the triggerRemoteJob method.

**Comment by quilicicf** [comment]
Of course, it'd look something like this:
```groovy
triggerRemoteJob(
  remoteJenkinsName: 'My instance name',
  job: 'build-thingy',
  useCrumbCache: true,
  useJobInfoCache: true,
  parameters: [
    PARAM_SINGLE_LINE: 'titi',
    PARAM_MULTI_LINE: '''
      Line 1
      Line 2
    '''
  ])
```

**Pull request merged**
