### PR TITLE
If console output looks like it might be JSON but it turns out it isn't, return the ConnectionResponse.

### PR DESCRIPTION
**Pull request by helenabutowatep**
This provides a potential solution to https://issues.jenkins-ci.org/browse/JENKINS-59261

### CODE REVIEW

**Comment by cashlalala** [comment]
@helenabutowatep thank for your contribution, is there any testcase so that I could understand more about the real case? It seemed a good patch, but I can't really imagine the real world cases.

**Comment by helenabutowatep** [comment]
@cashlalala I don't have an exact test case. At this point we're seeing this exception being thrown in our server and the current suspicion is that it is a combination of the timestamps produced by the Timestamper plugin and a server under load (perhaps where the agents generates huge logs).

Here's a sample error message from one of the exceptions:
```
net.sf.json.JSONException: Expected a ',' or ']' at character 15 of [2019-10-30T13:49:49.275Z] using credential gitCredentialId
```

**Comment by helenabutowatep** [comment]
@cashlalala is there anything else required for this to get merged? With this fix in place, we haven't seen this exception being thrown in our Jenkins instances.

**Comment by cashlalala** [comment]
Okay, going to merge it. Being buszy recently.

**Comment by cybe** [comment]
Hi @helenabutowatep and @cashlalala,


to clarify on why this is happening: Since #54 the remote job log output is being streamed to the calling job. This is implemented by issuing multiple HTTP calls to the remote instance to grab that log. By pure chance one particular response string might begin with the character `[`, as we see with the timestamper plugin. And this is where the call to [JSONUtils.mayBeJSON](https://github.com/helenabutowatep/parameterized-remote-trigger-plugin/blob/d0f2739a6bf1387a1b9189390bb3aa5f3974608a/src/main/java/org/jenkinsci/plugins/ParameterizedRemoteTrigger/utils/HttpHelper.java#L524) detects that response [as possibly JSON](https://github.com/jenkinsci/json-lib/blob/16052d1f74908fb59430eddd73f42aec2469b313/src/main/java/net/sf/json/util/JSONUtils.java#L390).

**Comment by helenabutowatep** [comment]
@cashlalala when are you planning on releasing the next version of the plugin? It would be nice to be able to get this from the official repos instead of having to use an internal build.

**Comment by cashlalala** [comment]
@helenabutowatep v3.1.1 released, FYI

**Pull request merged**
